#!/usr/bin/env bash
set -uo pipefail

KIT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$KIT_DIR/.." && pwd)"
SOURCE_ROOT="$PROJECT_ROOT/Data-Structures"
MARKER="# Generated by shared-test-kit install.sh"

if [[ ! -d "$SOURCE_ROOT" ]]; then
  echo "Could not find $SOURCE_ROOT" >&2
  echo "Place shared-test-kit beside the real Data-Structures folder, then run this again." >&2
  exit 1
fi

write_wrapper() {
  local target="$1"
  local body="$2"

  if [[ -e "$target" ]] && ! grep -qF "$MARKER" "$target" 2>/dev/null; then
    echo "Refusing to overwrite existing file: $target" >&2
    echo "Move it aside or delete it first, then rerun ./shared-test-kit/install.sh" >&2
    exit 1
  fi

  printf '%s\n' "$body" > "$target"
  chmod 755 "$target"
}

write_wrapper "$PROJECT_ROOT/test" "#!/usr/bin/env bash
$MARKER
set -uo pipefail
ROOT_DIR=\"\$(cd \"\$(dirname \"\${BASH_SOURCE[0]}\")\" && pwd)\"
\"\$ROOT_DIR/shared-test-kit/test\" \"\$@\"
exit \$?"

write_wrapper "$PROJECT_ROOT/run_ds_tests.sh" "#!/usr/bin/env bash
$MARKER
set -uo pipefail
ROOT_DIR=\"\$(cd \"\$(dirname \"\${BASH_SOURCE[0]}\")\" && pwd)\"
\"\$ROOT_DIR/shared-test-kit/run_ds_tests.sh\" \"\$@\"
exit \$?"

LEGACY_DSTEST="$PROJECT_ROOT/dstest"
if [[ -e "$LEGACY_DSTEST" ]] && grep -qF "$MARKER" "$LEGACY_DSTEST" 2>/dev/null; then
  rm -f "$LEGACY_DSTEST"
fi


echo "Installed wrappers in: $PROJECT_ROOT"
echo "Use:"
echo "  ./test list 1"
